# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pharbst <pharbst@student.42heilbronn.de>   +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/11/13 03:19:38 by pharbst           #+#    #+#              #
#    Updated: 2023/11/13 03:19:39 by pharbst          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

