version: '3.1'

services:
  nginx:
    build: ./requirements/nginx
    image: nginx:Inception
    container_name: nginx
    restart: unless-stopped
    ports:
      - 443:443
    env_file:
      - ./.env
    volumes:
      - /Users/pharbst/wordpress:/var/www/html/wordpress
    networks:
      - docker_network
    depends_on:
      - wordpress
  wordpress:
    build: ./requirements/wordpress
    image: wordpress:Inception
    container_name: wordpress
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - /Users/pharbst/wordpress:/var/www/html/wordpress
    networks:
      - docker_network
    depends_on:
      - mariadb
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:Inception
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - /Users/pharbst/mariadb:/var/lib/mysql
    networks:
      - docker_network

networks:
  docker_network:
    driver: bridge