# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pharbst <pharbst@student.42heilbronn.de>   +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/11/13 03:19:38 by pharbst           #+#    #+#              #
#    Updated: 2023/11/13 03:19:39 by pharbst          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: '3.7'

services:
  nginx:
    build: ./srcs/requirements/nginx
    image: nginx
    container_name: nginx
    networks:
      - docker_network
    ports:
      - 443:443
    env_file:
      - .env
    volumes:
      - /home/pharbst/data/wordpress:/var/www/html/wordpress
    depends_on:
      - wordpress
    restart: always
  wordpress:
    build: ./srcs/requirements/wordpress
    image: wordpress
    container_name: wordpress
    networks:
      - docker_network
    env_file:
      - .env
    volumes:
      - /home/pharbst/data/wordpress:/var/www/html/wordpress
    depends_on:
      - mariadb
    restart: always
  mariadb:
    build: ./srcs/requirements/mariadb
    image: mariadb
    container_name: mariadb
    networks:
      - docker_network
    env_file:
      - .env
    volumes:
      - /home/pharbst/data/mariadb:/var/lib/mysql
    restart: always

networks:
  docker_network:
    driver: bridge