version: '3.1'

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    env_file:
      - ./.env
    volumes:
      - ~/Documents/Inception/mariadbtestvolume:/var/lib/mysql
    networks:
      - docker_network
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    env_file:
      - ./.env
    volumes: ~/Documents/Inception/wordpresstestvolume:/var/www/html/wordpress
    networks:
      - docker_network
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    env_file:
      - ./.env
    volumes:
      - ~/Documents/Inception/wordpresstestvolume:/var/www/html/wordpress
    networks:
      - docker_network

networks:
  docker_network:
    driver: bridge