# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pharbst <pharbst@student.42heilbronn.de>   +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/11/13 03:19:35 by pharbst           #+#    #+#              #
#    Updated: 2023/11/16 13:07:14 by pharbst          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM debian:buster

EXPOSE 443

RUN	apt update \
	&& apt install -y nginx openssl



ENTRYPOINT

CMD
